version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://abir:abir@db:5432/test
      - SESSION_SECRET=your-secret-key
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://app:4000
    command: npm run start

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: abir
      POSTGRES_PASSWORD: abir
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
